# Generated by Django 2.0.1 on 2018-01-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILSA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='lock_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
