# Generated by Django 2.0.1 on 2018-02-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILSA', '0002_locker_lock_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locker',
            name='card_uid',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='locker',
            name='check_out_time',
            field=models.TimeField(default=None, verbose_name='Time Checked Out'),
        ),
        migrations.AlterField(
            model_name='locker',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='locker',
            name='unlockable',
            field=models.BooleanField(default=False),
        ),
    ]
