# Generated by Django 2.0.1 on 2018-02-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILSA', '0003_auto_20180202_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='battery_level',
            field=models.IntegerField(default=100, max_length=100),
        ),
    ]
