# Generated by Django 2.0.2 on 2018-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ILSA', '0004_locker_battery_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='battery_level',
            field=models.IntegerField(default=100),
        ),
    ]
